# Generated by Django 5.1.3 on 2024-12-05 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_id", models.IntegerField()),
                ("message", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("archived", "Archived"),
                            ("unread", "Unread"),
                            ("read", "Read"),
                        ],
                        default="unread",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
