# Generated by Django 5.1.3 on 2024-12-05 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notification_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="status",
            field=models.CharField(
                choices=[
                    ("read", "Read"),
                    ("unread", "Unread"),
                    ("archived", "Archived"),
                ],
                default="unread",
                max_length=10,
            ),
        ),
    ]
