services:
  auth_service:
    build:
      context: ./auth_service
    container_name: auth_service
    ports:
      - "8000:8000"
    networks:
      - backend
    env_file:
      - ./auth_service/.env
    depends_on:
      - postgres_auth_service

  user_profile_service:
    build:
      context: ./user_profile_service
    container_name: user_profile_service
    ports:
      - "8001:8001"
    networks:
      - backend
    env_file:
      - ./user_profile_service/.env
    depends_on:
      - postgres_user_profile_service
      - kafka

  video_service:
    build:
      context: ./video_service
    container_name: video_service
    ports:
      - "8002:8002"
    networks:
      - backend
    env_file:
      - ./video_service/.env
    depends_on:
      - postgres_video_service
      - kafka

  postgres_auth_service:
    image: postgres:latest
    container_name: auth_service_db
    environment:
      POSTGRES_DB: ${POSTGRES_NAME}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - auth_service_db_data:/var/lib/postgresql/data
    networks:
      - backend

  postgres_user_profile_service:
    image: postgres:latest
    container_name: user_profile_service_db
    environment:
      POSTGRES_DB: ${POSTGRES_NAME}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - user_profile_service_db_data:/var/lib/postgresql/data
    networks:
      - backend

  postgres_video_service:
    image: postgres:latest
    container_name: video_service_db
    environment:
      POSTGRES_DB: ${POSTGRES_NAME}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - video_service_db_data:/var/lib/postgresql/data
    networks:
      - backend

  kafka:
    image: wurstmeister/kafka:latest
    ports:
      - "9093:9093"
    environment:
      KAFKA_ADVERTISED_LISTENER: INSIDE://localhost:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL: PLAINTEXT
      KAFKA_LISTENER_INTERNAL: INSIDE://kafka:9093
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    depends_on:
      - zookeeper
    networks:
      - backend

  zookeeper:
    image: wurstmeister/zookeeper:latest
    ports:
      - "2181:2181"
    networks:
      - backend

networks:
  backend:
    driver: bridge

volumes:
  auth_service_db_data:
  user_profile_service_db_data:
  video_service_db_data:
