services:
  postgres_auth_service:
    image: postgres:latest
    container_name: auth_service_db_postgres
    env_file:
      - .env
    volumes:
      - auth_service_db_data:/var/lib/postgresql/data
    networks:
      - auth_service_network

  app:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - postgres_auth_service
      - redis
    env_file:
      - .env
    networks:
      - auth_service_network

  redis:
    image: redis
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - auth_service_network

volumes:
  auth_service_db_data:


networks:
  auth_service_network:
